### ISSUE TITLE
[Coding Dojo] Full Cycle Game Developer

### ISSUE THREAD

**Issue by tolstenko** [InfiniBrains/Introduction-to-Game-Programming-With-CPP#2]
General topic about our first dojo. Read https://github.com/InfiniBrains/Introduction-to-Game-Programming-With-CPP/blob/main/dojo/Full-Cycle-SDL-Development.md or if the link is broken, https://github.com/InfiniBrains/Introduction-to-Game-Programming-With-CPP/commit/33f68792f377f51c4f9043ddfb4015c8a2a0f312#diff-d904c570ff2e40e7ead5b55b75224beaeaefec661b845295f99cb5480f826320

- I don't know how to program in c++ but am eager to learn how to code;
- I am already a developer but I want to learn to deliver faster;
- I want to create automated tests for games from ground up

**Comment by vikumm** [comment]
I want to create automated tests for games and apps

**Comment by MoisesFreitas1** [comment]
Espero aprender mais sobre CMAKE e SDL e como isso pode ser aplicado no desenvolvimento de jogos.

**Comment by Tjoker222** [comment]
I want to understand more about game development and automated tests

**Comment by rodrigomassanori** [comment]
interesse em estudar sdl integrado com opengl em c++, pelo vscode

**Comment by alecsantos96** [comment]
I want to able to easily create libraries based on a [C++ API](https://github.com/godotengine/godot-cpp)

**Comment by rodrigomassanori** [comment]
achei boa o assunto sobre c++, sdl e jogos, gostei muito

**Comment by tolstenko** [comment]
I am closing this issue just to keep the repo clean, but be my guest and continue adding stuff here. I just created empty dojo activities for everything you asked for here. Let's continue the discussion there.
@alecsantos96 see #3 
@rodrigomassanori #4
@Tjoker222 and @vikumm #5
@MoisesFreitas1 #6
